### ISSUE TITLE
Responsive : Register form - Form is asking to fill password field correctly, even if it is filled out correctly. Unable to complete registration. 

### ISSUE THREAD

**Issue by mclarkecci** [CCI-Studios/ICSA#18]

**Comment by hemantcci** [comment]
Can you tell me the password you tried when it denied.

**Comment by mclarkecci** [comment]
I've tried a few different ones.
Testing123- 
testcci123>

**Comment by hemantcci** [comment]
I have added allowed special characters in password description. '>' is not allowed, I have included '-' though. You can try now
